<a href="https://cognitiveclass.ai"><img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DL0101EN-SkillsNetwork/images/IDSN-logo.png" width="400"> </a>

# Keras ile Regresyon Modelleri

Tahmini süre: **45** dakika

## Introduction

Videolarda da tartıştığımız gibi, PyTorch ve TensorFlow gibi daha güçlü kütüphanelerin popülaritesine rağmen, kullanımları kolay değil ve öğrenme eğrileri dik. Bu nedenle, derin öğrenmeye yeni başlayanlar için Keras kütüphanesinden daha iyi bir kütüphane yok.

Keras, derin öğrenme modelleri oluşturmak için yüksek seviyeli bir API'dir. Kullanım kolaylığı ve sözdizimsel basitliği sayesinde hızlı geliştirmeyi kolaylaştırdığı için beğeni kazanmıştır. Bu laboratuvarda ve bu kursun diğer laboratuvarlarında göreceğiniz gibi, Keras ile sadece birkaç satır kodla çok karmaşık bir derin öğrenme ağı oluşturmak mümkün. Diğer kurslarda PyTorch ve TensorFlow kullanarak derin modeller oluşturmayı öğrendikten sonra Keras'ı daha da çok takdir edeceksiniz.

Bu nedenle, bu laboratuvarda, Keras kütüphanesini kullanarak bir regresyon modeli oluşturmayı öğreneceksiniz.

## Bu Notebook'un Amaçları
* Keras kütüphanesini kullanarak bir regresyon modeli oluşturma
* Veri setini indirme ve temizleme
* Bir sinir ağı oluşturma
* Ağı eğitme ve test etme

<h2>İçindekiler</h2>

<div class="alert alert-block alert-info" style="margin-top: 20px">

<font size = 4>
1. <a href="#Veri Kümesini İndir ve Temizle">Veri Kümesini İndir ve Temizle</a><br>
2. <a href="#Keras Paketlerini İçe Aktar">Keras Paketlerini İçe Aktar</a><br>
3. <a href="#Sinir Ağı Oluştur">Sinir Ağı Oluştur</a><br>
4. <a href="#Ağı Eğit ve Test Et">Ağı Eğit ve Test Et</a><br>

</font>
</div>

Let's start by importing the <em>pandas</em> and the Numpy libraries.

In [3]:
# All Libraries required for this lab are listed below. 

!pip install numpy==2.0.2
!pip install pandas==2.2.2
!pip install tensorflow_cpu==2.18.0

Collecting numpy==2.0.2
  Downloading numpy-2.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Downloading numpy-2.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.2/19.2 MB 126.2 MB/s eta 0:00:00
Installing collected packages: numpy
Successfully installed numpy-2.0.2
Collecting pandas==2.2.2
  Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/lib/python3.12/site-packages (from pandas==2.2.2) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas==2.2.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas==2.2.2) (2024.2)
Collecting tzdata>=2022.7 (from pandas==2.2.2)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.2.2) (1.17.0)
Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 78.6 MB/s eta 0:00:00
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas
Successfully installed pandas-2.2.2 tzdata-2025.3
Collecting tensorflow_cpu==2.18.0
  Downloading tensorflow_cpu-2.18.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting absl-py>=1.0.0 (from tensorflow_cpu==2.18.0)
  Downloading absl_py-2.4.0-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow_cpu==2.18.0)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=24.3.25 (from tensorflow_cpu==2.18.0)
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow_cpu==2.18.0)
  Downloading gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google-pasta>=0.1.1 (from tensorflow_cpu==2.18.0)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow_cpu==2.18.0)
  Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
Collecting opt-einsum>=2.3.2 (from tensorflow_cpu==2.18.0)
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (24.2)
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 (from tensorflow_cpu==2.18.0)
  Downloading protobuf-5.29.6-cp38-abi3-manylinux2014_x86_64.whl.metadata (592 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (2.32.3)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (75.8.0)
Requirement already satisfied: six>=1.12.0 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow_cpu==2.18.0)
  Downloading termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing-extensions>=3.6.6 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (4.12.2)
Collecting wrapt>=1.11.0 (from tensorflow_cpu==2.18.0)
  Downloading wrapt-2.1.2-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (7.4 kB)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow_cpu==2.18.0)
  Downloading grpcio-1.78.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.8 kB)
Collecting tensorboard<2.19,>=2.18 (from tensorflow_cpu==2.18.0)
  Downloading tensorboard-2.18.0-py3-none-any.whl.metadata (1.6 kB)
Collecting keras>=3.5.0 (from tensorflow_cpu==2.18.0)
  Downloading keras-3.13.2-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: numpy<2.1.0,>=1.26.0 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (2.0.2)
Collecting h5py>=3.11.0 (from tensorflow_cpu==2.18.0)
  Downloading h5py-3.16.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Collecting ml-dtypes<0.5.0,>=0.4.0 (from tensorflow_cpu==2.18.0)
  Downloading ml_dtypes-0.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /opt/conda/lib/python3.12/site-packages (from astunparse>=1.6.0->tensorflow_cpu==2.18.0) (0.45.1)
Collecting rich (from keras>=3.5.0->tensorflow_cpu==2.18.0)
  Downloading rich-14.3.3-py3-none-any.whl.metadata (18 kB)
Collecting namex (from keras>=3.5.0->tensorflow_cpu==2.18.0)
  Downloading namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.5.0->tensorflow_cpu==2.18.0)
  Downloading optree-0.19.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (34 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow_cpu==2.18.0) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow_cpu==2.18.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow_cpu==2.18.0) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow_cpu==2.18.0) (2024.12.14)
Collecting markdown>=2.6.8 (from tensorboard<2.19,>=2.18->tensorflow_cpu==2.18.0)
  Downloading markdown-3.10.2-py3-none-any.whl.metadata (5.1 kB)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.19,>=2.18->tensorflow_cpu==2.18.0)
  Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
Collecting werkzeug>=1.0.1 (from tensorboard<2.19,>=2.18->tensorflow_cpu==2.18.0)
  Downloading werkzeug-3.1.6-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: markupsafe>=2.1.1 in /opt/conda/lib/python3.12/site-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow_cpu==2.18.0) (3.0.2)
Collecting markdown-it-py>=2.2.0 (from rich->keras>=3.5.0->tensorflow_cpu==2.18.0)
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.12/site-packages (from rich->keras>=3.5.0->tensorflow_cpu==2.18.0) (2.19.1)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow_cpu==2.18.0)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading tensorflow_cpu-2.18.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (230.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 230.3/230.3 MB 42.2 MB/s eta 0:00:0000:0100:01
Downloading absl_py-2.4.0-py3-none-any.whl (135 kB)
Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Downloading flatbuffers-25.12.19-py2.py3-none-any.whl (26 kB)
Downloading gast-0.7.0-py3-none-any.whl (22 kB)
Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
Downloading grpcio-1.78.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (6.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 43.6 MB/s eta 0:00:00
Downloading h5py-3.16.0-cp312-cp312-manylinux_2_28_x86_64.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 48.1 MB/s eta 0:00:00
Downloading keras-3.13.2-py3-none-any.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 44.8 MB/s eta 0:00:00
Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 48.0 MB/s eta 0:00:00:00:01
Downloading ml_dtypes-0.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 53.9 MB/s eta 0:00:00
Downloading opt_einsum-3.4.0-py3-none-any.whl (71 kB)
Downloading protobuf-5.29.6-cp38-abi3-manylinux2014_x86_64.whl (320 kB)
Downloading tensorboard-2.18.0-py3-none-any.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 50.5 MB/s eta 0:00:00
Downloading termcolor-3.3.0-py3-none-any.whl (7.7 kB)
Downloading wrapt-2.1.2-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (121 kB)
Downloading markdown-3.10.2-py3-none-any.whl (108 kB)
Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 54.3 MB/s eta 0:00:00
Downloading werkzeug-3.1.6-py3-none-any.whl (225 kB)
Downloading namex-0.1.0-py3-none-any.whl (5.9 kB)
Downloading optree-0.19.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (451 kB)
Downloading rich-14.3.3-py3-none-any.whl (310 kB)
Downloading markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: namex, libclang, flatbuffers, wrapt, werkzeug, termcolor, tensorboard-data-server, protobuf, optree, opt-einsum, ml-dtypes, mdurl, markdown, h5py, grpcio, google-pasta, gast, astunparse, absl-py, tensorboard, markdown-it-py, rich, keras, tensorflow_cpu
Successfully installed absl-py-2.4.0 astunparse-1.6.3 flatbuffers-25.12.19 gast-0.7.0 google-pasta-0.2.0 grpcio-1.78.0 h5py-3.16.0 keras-3.13.2 libclang-18.1.1 markdown-3.10.2 markdown-it-py-4.0.0 mdurl-0.1.2 ml-dtypes-0.4.1 namex-0.1.0 opt-einsum-3.4.0 optree-0.19.0 protobuf-5.29.6 rich-14.3.3 tensorboard-2.18.0 tensorboard-data-server-0.7.2 tensorflow_cpu-2.18.0 termcolor-3.3.0 werkzeug-3.1.6 wrapt-2.1.2

#### Keras'ı kullanmak için, TensorFlow gibi bir arka uç çerçevesi de kurmanız gerekecektir.

TensorFlow 2.16 veya üstünü kurarsanız, Keras varsayılan olarak kurulacaktır.

Daha küçük veri kümeleriyle çalıştığımız için TensorFlow'un CPU sürümünü kullanıyoruz.

Daha büyük veri kümelerinin işlenmesini hızlandırmak için makinenize TensorFlow'un GPU sürümünü kurabilirsiniz.

#### TensorFlow uyarı mesajlarını bastırma
TensorFlow için CPU mimarisi kullanımından kaynaklanan uyarı mesajlarını bastırmak için aşağıdaki kodu kullanıyoruz.

GPU mimarisi kullanıyorsanız bu satırları **yorum satırı haline getirmek** isteyebilirsiniz.

In [4]:
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [5]:
import pandas as pd
import numpy as np
import keras

import warnings
warnings.simplefilter('ignore', FutureWarning)

Videolarda kullandığımız aynı veri setini kullanacağız.

<strong>Veri seti, farklı beton örneklerinin, yapımında kullanılan farklı bileşenlerin hacimlerine bağlı olarak basınç dayanımıyla ilgilidir. Bileşenler şunlardır:</strong>

* Çimento
* Yüksek fırın cürufu
* Uçucu kül
* Su
* Süper akışkanlaştırıcı
* İri agrega
* İnce agrega

## Download and Clean the Data Set

Let's download the data and read it into a <em>pandas</em> dataframe.

In [6]:
filepath='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv'
concrete_data = pd.read_csv(filepath)

concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

İlk beton numunesinde 540 metreküp çimento, 0 metreküp yüksek fırın cürufu, 0 metreküp uçucu kül, 162 metreküp su, 2,5 metreküp süperplastikleştirici, 1040 metreküp iri agrega ve 676 metreküp ince agrega bulunmaktadır. 28 günlük bu beton karışımının basınç dayanımı 79,99 MPa'dır.

#### Let's check how many data points we have

In [7]:
concrete_data.shape

(1030, 9)

Dolayısıyla, modelimizi eğitmek için yaklaşık 1000 örnek bulunmaktadır. Örnek sayısının az olması nedeniyle, eğitim verilerine aşırı uyum sağlamamaya dikkat etmeliyiz.

Let's check the dataset for any missing values.

In [8]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [9]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

The data looks very clean and is ready to be used to build our model.

#### Split data into predictors and target

Bu problemdeki hedef değişken beton numunesinin dayanımıdır. Dolayısıyla, tahmin edicilerimiz diğer tüm sütunlar olacaktır.

In [10]:
concrete_data_columns = concrete_data.columns

In [12]:
predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # Güç hariç tüm sütunlar
target = concrete_data['Strength'] # Strength column

<a id="item2"></a>

Let's do a quick sanity check of the predictors and the target dataframes.

In [13]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [14]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

Son olarak, son adım, ortalamayı çıkarıp standart sapmaya bölerek verileri normalleştirmektir.

In [15]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

Ağımızı oluştururken bu sayıya ihtiyacımız olacağı için, tahmin edici sayısını *n_cols* değişkenine kaydedelim.

In [17]:
n_cols = predictors_norm.shape[1] # number of predictors
print(n_cols)

8

<a id="item1"></a>

##  Import Keras Packages

##### Let's import the rest of the packages from the Keras library that we will need to build our regression model.

In [18]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Input

## Build a Neural Network

Let's define a function that defines our regression model for us so that we can conveniently call it to create our model.

In [19]:
# define regression model
def regression_model():                          # regresyon problemi için bir sinir ağı modeli oluşturan fonksiyon   
    model = Sequential()                         # katmanların sırayla eklendiği bir neural network modeli oluşturur   
    model.add(Input(shape=(n_cols,)))            # giriş katmanı: veri setindeki özellik (feature) sayısı kadar input alır    
    model.add(Dense(50, activation='relu'))      # 1. gizli katman: 50 nöron içerir, ReLU aktivasyonu kullanır      
    model.add(Dense(1))                          # çıkış katmanı: tek bir sayısal değer üretir (regression çıktısı)    
    model.compile(optimizer='adam',              # optimizer: Adam algoritması ile ağırlıkları günceller
                  loss='mean_squared_error')     # loss fonksiyonu: tahmin ile gerçek değer arasındaki hatayı MSE ile ölçer   
    return model                                 # oluşturulan modeli fonksiyonun çıktısı olarak döndürür

Yukarıdaki fonksiyon, her biri 50 gizli birimden oluşan iki gizli katmana sahip bir model oluşturur.

## Ağı Eğitin ve Test Edin

Şimdi modelimizi oluşturmak için fonksiyonu çağıralım.

In [20]:
# build the model
model = regression_model()

Ardından, *fit* yöntemini kullanarak modeli aynı anda eğitecek ve test edeceğiz. Verilerin %30'unu doğrulama için ayıracağız ve modeli 100 epoch boyunca eğiteceğiz.

In [21]:
# fit the model
model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Epoch 1/100
23/23 - 1s - 39ms/step - loss: 1716.1414 - val_loss: 1232.3777
Epoch 2/100
23/23 - 0s - 7ms/step - loss: 1676.4047 - val_loss: 1203.9286
Epoch 3/100
23/23 - 0s - 7ms/step - loss: 1635.6422 - val_loss: 1174.5001
Epoch 4/100
23/23 - 0s - 7ms/step - loss: 1593.1467 - val_loss: 1143.5619
Epoch 5/100
23/23 - 0s - 7ms/step - loss: 1546.0172 - val_loss: 1110.6031
Epoch 6/100
23/23 - 0s - 6ms/step - loss: 1494.5767 - val_loss: 1075.6281
Epoch 7/100
23/23 - 0s - 6ms/step - loss: 1437.6556 - val_loss: 1037.7419
Epoch 8/100
23/23 - 0s - 6ms/step - loss: 1375.4891 - val_loss: 995.6945
Epoch 9/100
23/23 - 0s - 6ms/step - loss: 1306.4540 - val_loss: 951.4463
Epoch 10/100
23/23 - 0s - 6ms/step - loss: 1233.3306 - val_loss: 902.7948
Epoch 11/100
23/23 - 0s - 6ms/step - loss: 1153.9609 - val_loss: 853.1514
Epoch 12/100
23/23 - 0s - 6ms/step - loss: 1072.0830 - val_loss: 800.3591
Epoch 13/100
23/23 - 0s - 6ms/step - loss: 987.4769 - val_loss: 747.5723
Epoch 14/100
23/23 - 0s - 6ms/step - loss: 903.5406 - val_loss: 691.8066
Epoch 15/100
23/23 - 0s - 6ms/step - loss: 818.3831 - val_loss: 639.5242
Epoch 16/100
23/23 - 0s - 6ms/step - loss: 737.1132 - val_loss: 586.8526
Epoch 17/100
23/23 - 0s - 6ms/step - loss: 659.7667 - val_loss: 536.0037
Epoch 18/100
23/23 - 0s - 6ms/step - loss: 587.2596 - val_loss: 489.6301
Epoch 19/100
23/23 - 0s - 6ms/step - loss: 522.6984 - val_loss: 446.1196
Epoch 20/100
23/23 - 0s - 6ms/step - loss: 464.4290 - val_loss: 406.2029
Epoch 21/100
23/23 - 0s - 6ms/step - loss: 413.7999 - val_loss: 370.7296
Epoch 22/100
23/23 - 0s - 7ms/step - loss: 370.9822 - val_loss: 338.9738
Epoch 23/100
23/23 - 0s - 6ms/step - loss: 334.1398 - val_loss: 313.1259
Epoch 24/100
23/23 - 0s - 6ms/step - loss: 304.6219 - val_loss: 290.2377
Epoch 25/100
23/23 - 0s - 6ms/step - loss: 280.1855 - val_loss: 271.1818
Epoch 26/100
23/23 - 0s - 6ms/step - loss: 261.0987 - val_loss: 255.2869
Epoch 27/100
23/23 - 0s - 6ms/step - loss: 245.8375 - val_loss: 241.9082
Epoch 28/100
23/23 - 0s - 6ms/step - loss: 233.5974 - val_loss: 232.4641
Epoch 29/100
23/23 - 0s - 6ms/step - loss: 223.9711 - val_loss: 223.7234
Epoch 30/100
23/23 - 0s - 6ms/step - loss: 216.4510 - val_loss: 215.9402
Epoch 31/100
23/23 - 0s - 6ms/step - loss: 210.2623 - val_loss: 210.7920
Epoch 32/100
23/23 - 0s - 6ms/step - loss: 205.3577 - val_loss: 205.9766
Epoch 33/100
23/23 - 0s - 6ms/step - loss: 201.3093 - val_loss: 202.0772
Epoch 34/100
23/23 - 0s - 6ms/step - loss: 197.6143 - val_loss: 199.5437
Epoch 35/100
23/23 - 0s - 6ms/step - loss: 194.4359 - val_loss: 197.2066
Epoch 36/100
23/23 - 0s - 7ms/step - loss: 191.4848 - val_loss: 193.8292
Epoch 37/100
23/23 - 0s - 6ms/step - loss: 189.1848 - val_loss: 191.4628
Epoch 38/100
23/23 - 0s - 6ms/step - loss: 186.8616 - val_loss: 189.2759
Epoch 39/100
23/23 - 0s - 6ms/step - loss: 184.6035 - val_loss: 187.4357
Epoch 40/100
23/23 - 0s - 6ms/step - loss: 182.5972 - val_loss: 186.0736
Epoch 41/100
23/23 - 0s - 6ms/step - loss: 180.6792 - val_loss: 184.5837
Epoch 42/100
23/23 - 0s - 6ms/step - loss: 178.9842 - val_loss: 183.3450
Epoch 43/100
23/23 - 0s - 6ms/step - loss: 177.2656 - val_loss: 180.7178
Epoch 44/100
23/23 - 0s - 7ms/step - loss: 175.7082 - val_loss: 179.4403
Epoch 45/100
23/23 - 0s - 6ms/step - loss: 174.1907 - val_loss: 177.6519
Epoch 46/100
23/23 - 0s - 6ms/step - loss: 172.7838 - val_loss: 177.2449
Epoch 47/100
23/23 - 0s - 5ms/step - loss: 171.0423 - val_loss: 174.8309
Epoch 48/100
23/23 - 0s - 5ms/step - loss: 169.7629 - val_loss: 173.2941
Epoch 49/100
23/23 - 0s - 6ms/step - loss: 168.6425 - val_loss: 170.9672
Epoch 50/100
23/23 - 0s - 6ms/step - loss: 166.9412 - val_loss: 170.1451
Epoch 51/100
23/23 - 0s - 6ms/step - loss: 165.5376 - val_loss: 168.7918
Epoch 52/100
23/23 - 0s - 8ms/step - loss: 164.1899 - val_loss: 166.6818
Epoch 53/100
23/23 - 0s - 7ms/step - loss: 163.0235 - val_loss: 166.1665
Epoch 54/100
23/23 - 0s - 7ms/step - loss: 161.6126 - val_loss: 164.1900
Epoch 55/100
23/23 - 0s - 6ms/step - loss: 160.4240 - val_loss: 162.8444
Epoch 56/100
23/23 - 0s - 6ms/step - loss: 159.1859 - val_loss: 161.9937
Epoch 57/100
23/23 - 0s - 6ms/step - loss: 157.9274 - val_loss: 160.8695
Epoch 58/100
23/23 - 0s - 6ms/step - loss: 156.6775 - val_loss: 158.4656
Epoch 59/100
23/23 - 0s - 11ms/step - loss: 155.3855 - val_loss: 156.3634
Epoch 60/100
23/23 - 0s - 11ms/step - loss: 154.4875 - val_loss: 155.6735
Epoch 61/100
23/23 - 0s - 7ms/step - loss: 152.9839 - val_loss: 154.7946
Epoch 62/100
23/23 - 0s - 8ms/step - loss: 151.7180 - val_loss: 152.1246
Epoch 63/100
23/23 - 0s - 6ms/step - loss: 150.3455 - val_loss: 150.9459
Epoch 64/100
23/23 - 0s - 6ms/step - loss: 149.0131 - val_loss: 148.8289
Epoch 65/100
23/23 - 0s - 6ms/step - loss: 147.7837 - val_loss: 146.8167
Epoch 66/100
23/23 - 0s - 5ms/step - loss: 146.3918 - val_loss: 146.0520
Epoch 67/100
23/23 - 0s - 5ms/step - loss: 145.1964 - val_loss: 145.1535
Epoch 68/100
23/23 - 0s - 6ms/step - loss: 143.7043 - val_loss: 143.4430
Epoch 69/100
23/23 - 0s - 6ms/step - loss: 142.2985 - val_loss: 141.3994
Epoch 70/100
23/23 - 0s - 6ms/step - loss: 140.8690 - val_loss: 139.3492
Epoch 71/100
23/23 - 0s - 6ms/step - loss: 139.5027 - val_loss: 138.4270
Epoch 72/100
23/23 - 0s - 6ms/step - loss: 137.9820 - val_loss: 137.1054
Epoch 73/100
23/23 - 0s - 5ms/step - loss: 136.3555 - val_loss: 136.0867
Epoch 74/100
23/23 - 0s - 6ms/step - loss: 134.9194 - val_loss: 134.8401
Epoch 75/100
23/23 - 0s - 6ms/step - loss: 133.2541 - val_loss: 132.5796
Epoch 76/100
23/23 - 0s - 6ms/step - loss: 131.7917 - val_loss: 131.4863
Epoch 77/100
23/23 - 0s - 7ms/step - loss: 130.0747 - val_loss: 130.0351
Epoch 78/100
23/23 - 0s - 6ms/step - loss: 128.4861 - val_loss: 128.2715
Epoch 79/100
23/23 - 0s - 7ms/step - loss: 126.8460 - val_loss: 126.7199
Epoch 80/100
23/23 - 0s - 7ms/step - loss: 125.2751 - val_loss: 125.0883
Epoch 81/100
23/23 - 0s - 7ms/step - loss: 123.5586 - val_loss: 123.4290
Epoch 82/100
23/23 - 0s - 7ms/step - loss: 121.8595 - val_loss: 122.4368
Epoch 83/100
23/23 - 0s - 6ms/step - loss: 120.2684 - val_loss: 121.0318
Epoch 84/100
23/23 - 0s - 6ms/step - loss: 118.6583 - val_loss: 119.9365
Epoch 85/100
23/23 - 0s - 6ms/step - loss: 116.9175 - val_loss: 119.0536
Epoch 86/100
23/23 - 0s - 6ms/step - loss: 115.3430 - val_loss: 117.5957
Epoch 87/100
23/23 - 0s - 7ms/step - loss: 113.7563 - val_loss: 117.6221
Epoch 88/100
23/23 - 0s - 6ms/step - loss: 112.0707 - val_loss: 115.8416
Epoch 89/100
23/23 - 0s - 6ms/step - loss: 110.4914 - val_loss: 114.1010
Epoch 90/100
23/23 - 0s - 6ms/step - loss: 108.8061 - val_loss: 113.7723
Epoch 91/100
23/23 - 0s - 6ms/step - loss: 107.3226 - val_loss: 112.6048
Epoch 92/100
23/23 - 0s - 6ms/step - loss: 105.4478 - val_loss: 111.7143
Epoch 93/100
23/23 - 0s - 6ms/step - loss: 103.8231 - val_loss: 110.5786
Epoch 94/100
23/23 - 0s - 6ms/step - loss: 102.3368 - val_loss: 109.9260
Epoch 95/100
23/23 - 0s - 7ms/step - loss: 100.7818 - val_loss: 109.1565
Epoch 96/100
23/23 - 0s - 6ms/step - loss: 99.5854 - val_loss: 108.7935
Epoch 97/100
23/23 - 0s - 6ms/step - loss: 97.9069 - val_loss: 107.5722
Epoch 98/100
23/23 - 0s - 6ms/step - loss: 96.3337 - val_loss: 107.2390
Epoch 99/100
23/23 - 0s - 6ms/step - loss: 95.0144 - val_loss: 105.6136
Epoch 100/100
23/23 - 0s - 6ms/step - loss: 93.5148 - val_loss: 106.0019

<strong>Tahmin veya değerlendirme için kullanabileceğiniz diğer işlevler hakkında bilgi edinmek için bu [bağlantıya](https://keras.io/models/sequential/) bakabilirsiniz.</strong>

Aşağıdakileri değiştirmekte ve her değişikliğin modelin performansına etkisini not etmekte özgürsünüz:

1. Gizli katmanlardaki nöron sayısını artırın veya azaltın
2. Daha fazla gizli katman ekleyin
3. Epoch sayısını artırın

<h3>Practice Exercise 1</h3>

Şimdi aynı veri setini kullanarak, her biri 50 düğümlü ve ReLU aktivasyon fonksiyonlu beş gizli katmana, tek bir çıkış katmanına sahip ve Adam optimizasyon algoritması kullanılarak optimize edilmiş bir regresyon modeli oluşturmayı deneyin.

In [ ]:
def regression_model():
    input_colm = predictors_norm.shape[1] 
    # create model
    model = Sequential()
    model.add(Input(shape=(input_colm,)))  
    model.add(Dense(50, activation='relu'))  
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu')) 
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))  
    model.add(Dense(1))  # Output layer
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

Double-click <b>here</b> for the solution.

<!-- Your answer is below:
def regression_model():
    input_colm = predictors_norm.shape[1] # Number of input features
    # create model
    model = Sequential()
    model.add(Input(shape=(input_colm,)))  # Set the number of input features 
    model.add(Dense(50, activation='relu'))  
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu')) 
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))  
    model.add(Dense(1))  # Output layer
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

-->

<h3>Practice Exercise 2</h3>

Verilerin %10'unu doğrulama için ayırarak ve modeli 100 epoch boyunca eğiterek, fit() yöntemini kullanarak modeli eş zamanlı olarak eğitin ve değerlendirin.

In [22]:
model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Epoch 1/100
23/23 - 0s - 8ms/step - loss: 92.1692 - val_loss: 104.8121
Epoch 2/100
23/23 - 0s - 6ms/step - loss: 90.7458 - val_loss: 104.4025
Epoch 3/100
23/23 - 0s - 6ms/step - loss: 89.4379 - val_loss: 102.9142
Epoch 4/100
23/23 - 0s - 6ms/step - loss: 88.1720 - val_loss: 101.9091
Epoch 5/100
23/23 - 0s - 6ms/step - loss: 87.0242 - val_loss: 101.3236
Epoch 6/100
23/23 - 0s - 6ms/step - loss: 85.5682 - val_loss: 101.5918
Epoch 7/100
23/23 - 0s - 6ms/step - loss: 84.2233 - val_loss: 100.3918
Epoch 8/100
23/23 - 0s - 6ms/step - loss: 82.9011 - val_loss: 101.4206
Epoch 9/100
23/23 - 0s - 7ms/step - loss: 81.7394 - val_loss: 99.8848
Epoch 10/100
23/23 - 0s - 6ms/step - loss: 80.6396 - val_loss: 98.5441
Epoch 11/100
23/23 - 0s - 6ms/step - loss: 79.3283 - val_loss: 99.7539
Epoch 12/100
23/23 - 0s - 6ms/step - loss: 78.2448 - val_loss: 98.8277
Epoch 13/100
23/23 - 0s - 6ms/step - loss: 77.2400 - val_loss: 98.6174
Epoch 14/100
23/23 - 0s - 6ms/step - loss: 76.0575 - val_loss: 97.9285
Epoch 15/100
23/23 - 0s - 6ms/step - loss: 74.9839 - val_loss: 98.0612
Epoch 16/100
23/23 - 0s - 7ms/step - loss: 73.9075 - val_loss: 97.0004
Epoch 17/100
23/23 - 0s - 8ms/step - loss: 73.0207 - val_loss: 98.2454
Epoch 18/100
23/23 - 0s - 7ms/step - loss: 71.9081 - val_loss: 97.2342
Epoch 19/100
23/23 - 0s - 6ms/step - loss: 70.9470 - val_loss: 96.1730
Epoch 20/100
23/23 - 0s - 7ms/step - loss: 70.0384 - val_loss: 96.6666
Epoch 21/100
23/23 - 0s - 6ms/step - loss: 69.2149 - val_loss: 96.3096
Epoch 22/100
23/23 - 0s - 6ms/step - loss: 68.2849 - val_loss: 96.4507
Epoch 23/100
23/23 - 0s - 6ms/step - loss: 67.2206 - val_loss: 96.5766
Epoch 24/100
23/23 - 0s - 7ms/step - loss: 66.5455 - val_loss: 96.6535
Epoch 25/100
23/23 - 0s - 6ms/step - loss: 65.5217 - val_loss: 95.8919
Epoch 26/100
23/23 - 0s - 6ms/step - loss: 64.8651 - val_loss: 96.5510
Epoch 27/100
23/23 - 0s - 6ms/step - loss: 63.8743 - val_loss: 95.3790
Epoch 28/100
23/23 - 0s - 6ms/step - loss: 63.2655 - val_loss: 95.6601
Epoch 29/100
23/23 - 0s - 6ms/step - loss: 62.5579 - val_loss: 95.6589
Epoch 30/100
23/23 - 0s - 6ms/step - loss: 61.7526 - val_loss: 96.6096
Epoch 31/100
23/23 - 0s - 6ms/step - loss: 61.1762 - val_loss: 95.9466
Epoch 32/100
23/23 - 0s - 8ms/step - loss: 60.4221 - val_loss: 96.5179
Epoch 33/100
23/23 - 0s - 6ms/step - loss: 59.6569 - val_loss: 95.2137
Epoch 34/100
23/23 - 0s - 6ms/step - loss: 58.9760 - val_loss: 95.7526
Epoch 35/100
23/23 - 0s - 6ms/step - loss: 58.4461 - val_loss: 95.2207
Epoch 36/100
23/23 - 0s - 6ms/step - loss: 57.8005 - val_loss: 96.5717
Epoch 37/100
23/23 - 0s - 6ms/step - loss: 57.3346 - val_loss: 95.2583
Epoch 38/100
23/23 - 0s - 6ms/step - loss: 56.6371 - val_loss: 97.1538
Epoch 39/100
23/23 - 0s - 6ms/step - loss: 56.1364 - val_loss: 96.6116
Epoch 40/100
23/23 - 0s - 6ms/step - loss: 55.6012 - val_loss: 96.1629
Epoch 41/100
23/23 - 0s - 6ms/step - loss: 55.1518 - val_loss: 96.3438
Epoch 42/100
23/23 - 0s - 7ms/step - loss: 54.4112 - val_loss: 96.5156
Epoch 43/100
23/23 - 0s - 7ms/step - loss: 54.0821 - val_loss: 97.7061
Epoch 44/100
23/23 - 0s - 6ms/step - loss: 53.5036 - val_loss: 96.7454
Epoch 45/100
23/23 - 0s - 6ms/step - loss: 53.0422 - val_loss: 97.6945
Epoch 46/100
23/23 - 0s - 6ms/step - loss: 52.5398 - val_loss: 98.3335
Epoch 47/100
23/23 - 0s - 6ms/step - loss: 52.1041 - val_loss: 97.3635
Epoch 48/100
23/23 - 0s - 6ms/step - loss: 51.6197 - val_loss: 98.1764
Epoch 49/100
23/23 - 0s - 6ms/step - loss: 51.1556 - val_loss: 97.5256
Epoch 50/100
23/23 - 0s - 6ms/step - loss: 50.8891 - val_loss: 97.8141
Epoch 51/100
23/23 - 0s - 6ms/step - loss: 50.5438 - val_loss: 97.8263
Epoch 52/100
23/23 - 0s - 6ms/step - loss: 49.9846 - val_loss: 97.6671
Epoch 53/100
23/23 - 0s - 6ms/step - loss: 49.5572 - val_loss: 98.4083
Epoch 54/100
23/23 - 0s - 6ms/step - loss: 49.2341 - val_loss: 98.9222
Epoch 55/100
23/23 - 0s - 6ms/step - loss: 48.8372 - val_loss: 99.4007
Epoch 56/100
23/23 - 0s - 6ms/step - loss: 48.5339 - val_loss: 98.2355
Epoch 57/100
23/23 - 0s - 6ms/step - loss: 48.2178 - val_loss: 99.0032
Epoch 58/100
23/23 - 0s - 6ms/step - loss: 47.9162 - val_loss: 98.1006
Epoch 59/100
23/23 - 0s - 6ms/step - loss: 47.4816 - val_loss: 99.4449
Epoch 60/100
23/23 - 0s - 6ms/step - loss: 47.1914 - val_loss: 99.5419
Epoch 61/100
23/23 - 0s - 6ms/step - loss: 47.0524 - val_loss: 99.1523
Epoch 62/100
23/23 - 0s - 6ms/step - loss: 46.5555 - val_loss: 101.1051
Epoch 63/100
23/23 - 0s - 6ms/step - loss: 46.2099 - val_loss: 100.4476
Epoch 64/100
23/23 - 0s - 6ms/step - loss: 45.9201 - val_loss: 100.5485
Epoch 65/100
23/23 - 0s - 6ms/step - loss: 45.7342 - val_loss: 101.7029
Epoch 66/100
23/23 - 0s - 6ms/step - loss: 45.3513 - val_loss: 99.8684
Epoch 67/100
23/23 - 0s - 6ms/step - loss: 45.0144 - val_loss: 100.9937
Epoch 68/100
23/23 - 0s - 6ms/step - loss: 44.8389 - val_loss: 100.2597
Epoch 69/100
23/23 - 0s - 6ms/step - loss: 44.4783 - val_loss: 101.0610
Epoch 70/100
23/23 - 0s - 7ms/step - loss: 44.3429 - val_loss: 102.4887
Epoch 71/100
23/23 - 0s - 7ms/step - loss: 43.9738 - val_loss: 102.9096
Epoch 72/100
23/23 - 0s - 6ms/step - loss: 43.8242 - val_loss: 101.4236
Epoch 73/100
23/23 - 0s - 7ms/step - loss: 43.6533 - val_loss: 103.0082
Epoch 74/100
23/23 - 0s - 7ms/step - loss: 43.3111 - val_loss: 101.5835
Epoch 75/100
23/23 - 0s - 7ms/step - loss: 43.1002 - val_loss: 103.2280
Epoch 76/100
23/23 - 0s - 7ms/step - loss: 42.9087 - val_loss: 103.5120
Epoch 77/100
23/23 - 0s - 6ms/step - loss: 42.5761 - val_loss: 102.6571
Epoch 78/100
23/23 - 0s - 6ms/step - loss: 42.3635 - val_loss: 103.9721
Epoch 79/100
23/23 - 0s - 6ms/step - loss: 42.1769 - val_loss: 104.4002
Epoch 80/100
23/23 - 0s - 6ms/step - loss: 41.9443 - val_loss: 103.7241
Epoch 81/100
23/23 - 0s - 6ms/step - loss: 41.9143 - val_loss: 104.0393
Epoch 82/100
23/23 - 0s - 7ms/step - loss: 41.6389 - val_loss: 104.3315
Epoch 83/100
23/23 - 0s - 6ms/step - loss: 41.5128 - val_loss: 102.5652
Epoch 84/100
23/23 - 0s - 6ms/step - loss: 41.0855 - val_loss: 106.0693
Epoch 85/100
23/23 - 0s - 6ms/step - loss: 40.9076 - val_loss: 106.2969
Epoch 86/100
23/23 - 0s - 6ms/step - loss: 40.7669 - val_loss: 105.9486
Epoch 87/100
23/23 - 0s - 6ms/step - loss: 40.5461 - val_loss: 106.8413
Epoch 88/100
23/23 - 0s - 6ms/step - loss: 40.4377 - val_loss: 106.3000
Epoch 89/100
23/23 - 0s - 6ms/step - loss: 40.2654 - val_loss: 106.4677
Epoch 90/100
23/23 - 0s - 6ms/step - loss: 40.0879 - val_loss: 108.4828
Epoch 91/100
23/23 - 0s - 6ms/step - loss: 40.0387 - val_loss: 106.4572
Epoch 92/100
23/23 - 0s - 6ms/step - loss: 39.6417 - val_loss: 106.8483
Epoch 93/100
23/23 - 0s - 6ms/step - loss: 39.4674 - val_loss: 107.9723
Epoch 94/100
23/23 - 0s - 6ms/step - loss: 39.4512 - val_loss: 110.1079
Epoch 95/100
23/23 - 0s - 6ms/step - loss: 39.1856 - val_loss: 108.0103
Epoch 96/100
23/23 - 0s - 5ms/step - loss: 38.9935 - val_loss: 109.5055
Epoch 97/100
23/23 - 0s - 6ms/step - loss: 38.9548 - val_loss: 109.1691
Epoch 98/100
23/23 - 0s - 6ms/step - loss: 38.6391 - val_loss: 108.5289
Epoch 99/100
23/23 - 0s - 6ms/step - loss: 38.5586 - val_loss: 109.3742
Epoch 100/100
23/23 - 0s - 6ms/step - loss: 38.5620 - val_loss: 110.4185

Double-click <b>here</b> for the solution.

<!-- Your answer is below:
# build the model
model = regression_model()
model.fit(predictors_norm, target, validation_split=0.1, epochs=100, verbose=2)

-->

Sonuçlara dayanarak şunları fark ediyoruz:

- Modele daha fazla gizli katman eklemek, modelin veriler içindeki karmaşık ilişkileri öğrenme ve temsil etme kapasitesini artırır. Bu, modelin daha iyi tanımlama yapmasını sağlar ve sonuç olarak model, eğitim verilerine daha etkili bir şekilde uyum sağlar ve tahminlerini potansiyel olarak iyileştirir.

- Doğrulama için ayrılan veri kümesinin oranını azaltarak ve daha büyük bir bölümünü eğitim için kullanarak, modelin öğrenmek için daha fazla örneğe erişimi olur. Bu ek eğitim verisi, modelin altta yatan eğilimleri daha iyi anlamasına yardımcı olur ve bu da genel performansı iyileştirebilir.

### Thank you for completing this lab!

This notebook was created by [Alex Aklson](https://www.linkedin.com/in/aklson/). I hope you found this lab interesting and educational. Feel free to contact me if you have any questions!

<!--
## Change Log

|  Date (YYYY-MM-DD) |  Version | Changed By  |  Change Description |
|---|---|---|---|
| 2024-11-20  | 3.0  | Aman  |  Updated the library versions to current |
| 2020-09-21  | 2.0  | Srishti  |  Migrated Lab to Markdown and added to course repo in GitLab |



<hr>

## <h3 align="center"> © IBM Corporation. All rights reserved. <h3/>

## <h3 align="center"> &#169; IBM Corporation. All rights reserved. <h3/>